version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - smtp
    environment:
      FLASK_APP: app.app
      FLASK_ENV: development
      FLASK_DEBUG: 1
      MAIL_SERVER: smtp
      MAIL_PORT: 1025
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:root@mysql:3306/bankingapp
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    networks:
      - finservice_network
    command: flask run --host=0.0.0.0 --port=3000 --reload
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bankingapp             
      MYSQL_PASSWORD: root                   
      MYSQL_ROOT_PASSWORD: root              
    ports:
      - "3306:3306"
    healthcheck:  # Add healthcheck for MySQL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5                          
    networks:
      - finservice_network
    restart: always
    
  smtp:
    image: mailhog/mailhog
    container_name: smtp-1
    ports:
      - "1025:1025"  # MailHog SMTP port
      - "8025:8025"  # MailHog Web interface for viewing mails
    networks:
      - finservice_network
    restart: always


networks:
  finservice_network:
    driver: bridge