"""Add exchange fees and exchange rates tables

Revision ID: efa06d68f2de
Revises: 
Create Date: 2024-11-26 17:22:25.861444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa06d68f2de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_fees', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_currency_pair_fees', ['currency_from', 'currency_to'])

    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_currency_pair_rates', ['currency_from', 'currency_to'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_constraint('uix_currency_pair_rates', type_='unique')

    with op.batch_alter_table('exchange_fees', schema=None) as batch_op:
        batch_op.drop_constraint('uix_currency_pair_fees', type_='unique')

    # ### end Alembic commands ###
